#!/usr/bin/env julia
"""
    unify_notebooks.jl

Updates all Pluto notebooks to use a common Project.toml environment.
This script:
1. Reads a common Project.toml (generated by analyze_common_env.jl)
2. Updates PLUTO_PROJECT_TOML_CONTENTS in all notebooks
3. Optionally validates that notebooks can still be activated

Usage:
    julia services/unify_notebooks.jl [--project path/to/common_Project.toml] [--dry-run] [--validate]
"""

using Pkg
using Pluto
using TOML
using Logging
using Glob

"""
    find_notebooks_with_project_toml(root_dir::String = ".")

Find all notebooks containing PLUTO_PROJECT_TOML_CONTENTS.
"""
function find_notebooks_with_project_toml(root_dir::String=".")
    notebooks = String[]

    # Find all .jl files in notebooks/ and literate/ directories
    notebook_dirs = [
        joinpath(root_dir, "notebooks"),
        joinpath(root_dir, "literate"),
        joinpath(root_dir, "jupyter")
    ]

    for dir in notebook_dirs
        if isdir(dir)
            # Find all .jl files recursively (including root level)
            for file in vcat(glob("*.jl", dir), glob("**/*.jl", dir))
                try
                    content = read(file, String)
                    # Check if it's a Pluto notebook and has PLUTO_PROJECT_TOML_CONTENTS
                    if startswith(content, "### A Pluto.jl notebook ###") &&
                       occursin("PLUTO_PROJECT_TOML_CONTENTS", content)
                        push!(notebooks, file)
                    end
                catch e
                    @warn "Could not read $file: $e"
                end
            end
        end
    end

    return notebooks
end

"""
    update_notebook_project_toml(notebook_path::String, new_project_toml::String, new_manifest_toml::Union{String, Nothing} = nothing; dry_run::Bool = false)

Replace PLUTO_PROJECT_TOML_CONTENTS and optionally PLUTO_MANIFEST_TOML_CONTENTS in a notebook.
Returns (success::Bool, backup_path::Union{String, Nothing}).
"""
function update_notebook_project_toml(notebook_path::String, new_project_toml::String, new_manifest_toml::Union{String,Nothing}=nothing; dry_run::Bool=false)
    try
        content = read(notebook_path, String)

        # Find PLUTO_PROJECT_TOML_CONTENTS = """..."""
        project_pattern = r"(PLUTO_PROJECT_TOML_CONTENTS\s*=\s*\"\"\")(.*?)(\"\"\")"s

        if !occursin(project_pattern, content)
            @warn "Could not find PLUTO_PROJECT_TOML_CONTENTS in $notebook_path"
            return (false, nothing)
        end

        if dry_run
            println("   [DRY RUN] Would update: $(basename(notebook_path))")
            return (true, nothing)
        end

        # Create backup
        backup_path = notebook_path * ".backup"
        cp(notebook_path, backup_path; force=true)

        # Replace Project.toml content
        new_content = replace(content, project_pattern) do m
            m.captures[1] * new_project_toml * m.captures[3]
        end

        # Replace Manifest.toml content if provided and exists
        if !isnothing(new_manifest_toml) && occursin("PLUTO_MANIFEST_TOML_CONTENTS", new_content)
            manifest_pattern = r"(PLUTO_MANIFEST_TOML_CONTENTS\s*=\s*\"\"\")(.*?)(\"\"\")"s
            new_content = replace(new_content, manifest_pattern) do m
                m.captures[1] * new_manifest_toml * m.captures[3]
            end
        end

        # Write updated content
        write(notebook_path, new_content)

        return (true, backup_path)
    catch e
        @error "Error updating $notebook_path" exception = (e, catch_backtrace())
        return (false, nothing)
    end
end

"""
    validate_notebook(notebook_path::String)

Try to activate the notebook's environment to validate it works.
Returns (success::Bool, error::Union{Nothing, Exception}).
"""
function validate_notebook(notebook_path::String)
    try
        # Activate the notebook environment
        Pluto.activate_notebook_environment(notebook_path)

        # Try to resolve dependencies
        Pkg.resolve()

        return (true, nothing)
    catch e
        return (false, e)
    end
end

function main()
    # Parse command line arguments
    common_project_path = "common_Project.toml"
    common_manifest_path = nothing
    dry_run = false
    validate = false

    i = 1
    while i <= length(ARGS)
        arg = ARGS[i]
        if arg == "--project" && i < length(ARGS)
            common_project_path = ARGS[i+1]
            i += 2
        elseif arg == "--manifest" && i < length(ARGS)
            common_manifest_path = ARGS[i+1]
            i += 2
        elseif arg == "--dry-run"
            dry_run = true
            i += 1
        elseif arg == "--validate"
            validate = true
            i += 1
        elseif arg == "--help" || arg == "-h"
            println("""
            Usage: julia unify_notebooks.jl [OPTIONS]

            Options:
              --project PATH    Path to common Project.toml (default: common_Project.toml)
              --manifest PATH   Path to common Manifest.toml (auto-detected if not provided)
              --dry-run         Show what would be updated without making changes
              --validate        Validate each notebook after updating
              --help, -h        Show this help message
            """)
            return
        else
            println("Unknown option: $arg. Use --help for usage.")
            return
        end
    end

    # Check if common Project.toml exists
    if !isfile(common_project_path)
        error("Common Project.toml not found: $common_project_path")
    end

    # Auto-detect Manifest.toml if not provided
    if isnothing(common_manifest_path)
        # Try common locations
        possible_manifest = [
            replace(common_project_path, "Project.toml" => "Manifest.toml"),
            replace(common_project_path, ".toml" => "_Manifest.toml"),
            dirname(common_project_path) * "/Manifest.toml"
        ]
        for path in possible_manifest
            if isfile(path)
                common_manifest_path = path
                break
            end
        end
    end

    # Read common Project.toml
    println("📖 Reading common Project.toml from: $common_project_path")
    common_project_dict = TOML.parsefile(common_project_path)

    # Read common Manifest.toml if available
    common_manifest_content = nothing
    if !isnothing(common_manifest_path) && isfile(common_manifest_path)
        println("📖 Reading common Manifest.toml from: $common_manifest_path")
        common_manifest_content = read(common_manifest_path, String)
    else
        println("⚠️  No Manifest.toml found - will only update Project.toml")
        println("   (Pluto will regenerate Manifest when notebooks are opened)")
    end

    # Generate Project.toml string
    lines = String[]
    push!(lines, "[deps]")
    if haskey(common_project_dict, "deps")
        for name in sort(collect(keys(common_project_dict["deps"])))
            uuid = common_project_dict["deps"][name]
            push!(lines, "$name = \"$uuid\"")
        end
    end

    if haskey(common_project_dict, "compat") && !isempty(common_project_dict["compat"])
        push!(lines, "")
        push!(lines, "[compat]")
        for name in sort(collect(keys(common_project_dict["compat"])))
            version_spec = common_project_dict["compat"][name]
            push!(lines, "$name = \"$version_spec\"")
        end
    end

    new_project_toml = join(lines, "\n")

    println("   Found $(length(common_project_dict["deps"])) dependencies")
    if haskey(common_project_dict, "compat")
        println("   Found $(length(common_project_dict["compat"])) compat entries")
    end

    # Find all notebooks
    println("\n🔍 Finding notebooks with PLUTO_PROJECT_TOML_CONTENTS...")
    notebooks = find_notebooks_with_project_toml(".")
    println("   Found $(length(notebooks)) notebooks")

    if dry_run
        println("\n🔍 [DRY RUN] Would update the following notebooks:")
    else
        println("\n📝 Updating notebooks...")
    end

    # Track results
    updated = String[]
    failed = String[]
    backup_files = String[]

    for notebook in notebooks
        success, backup = update_notebook_project_toml(notebook, new_project_toml, common_manifest_content; dry_run=dry_run)

        if success
            push!(updated, notebook)
            if !isnothing(backup)
                push!(backup_files, backup)
            end
            println("   ✓ $(basename(notebook))")

            # Validate if requested
            if validate && !dry_run
                print("      Validating... ")
                valid, error = validate_notebook(notebook)
                if valid
                    println("✓")
                else
                    println("✗ Error: $error")
                end
            end
        else
            push!(failed, notebook)
            println("   ✗ $(basename(notebook))")
        end
    end

    # Summary
    println("\n" * "="^80)
    println("Summary:")
    println("="^80)
    println("   Total notebooks: $(length(notebooks))")
    println("   Updated: $(length(updated))")
    println("   Failed: $(length(failed))")

    if !isempty(failed)
        println("\n⚠️  Failed notebooks:")
        for nb in failed
            println("   - $nb")
        end
    end

    if !dry_run && !isempty(backup_files)
        println("\n💾 Backup files created:")
        for backup in backup_files
            println("   - $backup")
        end
        println("\n   You can restore from backups if needed.")
    end

    if dry_run
        println("\n💡 Run without --dry-run to apply changes.")
    else
        println("\n✅ Done! All notebooks updated to use common Project.toml.")
        if validate
            println("   Validation completed for all notebooks.")
        end
    end
end

# Run if executed directly
if abspath(PROGRAM_FILE) == abspath(@__FILE__)
    main()
end

